### ISSUE TITLE
Issue with generative command

### ISSUE THREAD

**Issue by danielfsbarreto** [justincampbell/generative#29]
Hey,

I am getting the following error while trying to run `generative` command:
```
▶ generative
/Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/lib/generative.rb:8:in `singleton class': uninitialized constant #<Class:Generative>::Forwardable (NameError)
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/lib/generative.rb:7:in `<module:Generative>'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/lib/generative.rb:3:in `<top (required)>'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/generative-0.2.4/bin/generative:5:in `<top (required)>'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/bin/generative:22:in `load'
        from /Users/danielbarreto/.rbenv/versions/2.3.3/bin/generative:22:in `<main>'
```

My current project can be found at this [repo](https://github.com/danielfsbarreto/property-based-tests/tree/generative). Is there something I am doing wrong? I did not find anything on the README. As far as I understood, it should magically work. 😄 

However, setting up `GENERATIVE_COUNT` manually seems to be functioning as expected:
```
▶ GENERATIVE_COUNT=10_000 bundle exec rspec spec/calculator_spec.rb

Calculator
  #add
    returns the sum of its arguments
    sums positive and negative values
    does nothing if sums value with zero
    left identity property (generative)
      example at ./spec/calculator_spec.rb:22
    right identity property (generative)
      example at ./spec/calculator_spec.rb:28
    commutativity property (generative)
      example at ./spec/calculator_spec.rb:35
    associativity property (generative)
      example at ./spec/calculator_spec.rb:43

Finished in 3.6 seconds (files took 0.08446 seconds to load)
40003 examples, 0 failures
```

**Comment by levionessa** [comment]
Hey @danielfsbarreto looks like #30 will get you fixed.

**Comment by danielfsbarreto** [comment]
Wonderful, @levionessa. Thanks!
